#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\BlogController::index
  methods: GET

login:
  path: /login
  controller: App\Controller\BlogController::login
  methods: GET

register:
  path: /register
  controller: App\Controller\BlogController::register
  methods: GET

home:
  path: /home
  controller: App\Controller\BlogController::home
  methods: GET